name: pred-geomap
channels:
  - conda-forge
dependencies:
  - autopep8
  - pylint
  - gdal
  - pywin32
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - tqdm
  - pip
  - imbalanced-learn
  - xgboost
  - pyside2
  - geopandas
